name       : check
version    : 0.14.0
release    : 10
source     :
    - https://github.com/libcheck/check/releases/download/0.14.0/check-0.14.0.tar.gz : bd0f0ca1be65b70238b32f8e9fe5d36dc2fbf7a759b7edf28e75323a7d74f30b
homepage   : https://libcheck.github.io/check/
license    : LGPL-2.1
component  : programming.library
summary    : C unit testing framework
description: |
    Check is a unit testing framework for C. It features a simple interface for defining unit tests, putting little in the way of the developer. Tests are run in a separate address space, so both assertion failures and code errors that cause segmentation faults or other signals can be caught. Test results are reportable in the following: Subunit, TAP, XML, and a generic logging format.
setup      : |
    # Fix usage with musl
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/include/musl
    for i in $installdir/usr/include/check*.h ; do
        ln -sv ../$(basename $i) $installdir/usr/include/musl/.
    done
check      : |
    %make check
