name       : check
homepage   : http://check.sourceforge.net/
version    : 0.11.0
release    : 6
source     :
    - https://github.com/libcheck/check/releases/download/0.11.0/check-0.11.0.tar.gz : 24f7a48aae6b74755bcbe964ce8bc7240f6ced2141f8d9cf480bc3b3de0d5616
license    : LGPL-2.0
component  : programming.library
summary    : C unit testing framework
description: |
    Check is a unit testing framework for C. It features a simple interface for defining unit tests, putting little in the way of the developer. Tests are run in a separate address space, so both assertion failures and code errors that cause segmentation faults or other signals can be caught. Test results are reportable in the following: Subunit, TAP, XML, and a generic logging format.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
