name       : check
homepage   : http://check.sourceforge.net/
version    : 0.9.14
release    : 5
source     :
    - http://downloads.sourceforge.net/project/check/check/0.9.14/check-0.9.14.tar.gz : c272624645b1b738cf57fd5d81a3e4d9b722b99d6133ee3f3c4007d4d279840a
license    : LGPL-2.0
summary    : C unit testing framework
description: |
    Check is a unit testing framework for C. It features a simple interface for defining unit tests, putting little in the way of the developer. Tests are run in a separate address space, so both assertion failures and code errors that cause segmentation faults or other signals can be caught. Test results are reportable in the following: Subunit, TAP, XML, and a generic logging format.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
